#' @title RelevantClones
#' @description Find clones with an increased frequency in phase2
#' @param table a data.frame generated by freqclones.py
#' @param frequency a cut-off value to consider a clone phase-specific
#' @return a data.frame with phase information
#' @examples
#' #do not run
#' TACOS::RelevandClones(table, frequency=15)
#' @export

RelevantClones <- function(table, frequency=15){
  
  phase <- c()
  
  for (i in 1:nrow(table)){
	
	sub_ <- subset(table, cluster == table$cluster[i])
	
	if (sub_$phase1 <= 1){
	  
	  phase[i] <- "phase2"
	  
	} else if (sub_$phase2 <= 1){
	  
	  phase[i] <- "phase1"
	  
	} else if (sub_$phase1 - sub_$phase2 > frequency){
	  
	  phase[i] <- "phase1"
	  
	} else if (sub_$phase1 - sub_$phase2 < -frequency){
	  
	  phase[i] <- "phase2"
	  
	} else {
	  
	  phase[i] <- "Not phase-specific clone"
	  
	}
	
  }
  
  table$phase <- phase
  return(table)	
}
